name: "Bug Report"
description: "Report unexpected behavior or a problem in the project."
labels: ["bug"]

body:
  - type: input
    id: summary
    attributes:
      label: "Short summary"
      description: "Briefly describe the bug."
      placeholder: "Example: Login API throws null reference error"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "List the steps needed to reproduce the issue."
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "Describe what should happen."
      placeholder: "The login API should return a valid token."

  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior"
      description: "Describe what actually happens."
      placeholder: "The API returns 500 Internal Server Error."

  - type: checkboxes
    id: goal
    attributes:
      label: "Goal of this issue"
      options:
        - label: "Fix the identified bug"
        - label: "Add regression test after fix"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Additional context"
      description: "Add logs, screenshots, or any related information."