-- Create UserMetricsHistory table for tracking weight and height over time
-- UPDATED: Uses bigint user_id to match public.User(id) instead of auth.users(id)

CREATE TABLE IF NOT EXISTS UserMetricsHistory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public."User"(id) ON DELETE CASCADE,
    weight_kg DECIMAL(5,2),
    height_cm DECIMAL(5,2),
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE UserMetricsHistory ENABLE ROW LEVEL SECURITY;

-- Create policy to allow users to see their own metrics
-- We need to join with User table to check auth.uid(), which is slightly more complex in RLS
-- OR we can rely on the backend to enforce privacy if RLS on joins is too heavy.
-- A common pattern when using a separate public ID is:
--   user_id IN (SELECT id FROM public."User" WHERE auth_id = auth.uid())

CREATE POLICY "Users can view their own metrics"
    ON UserMetricsHistory
    FOR SELECT
    USING (
        user_id IN (
            SELECT id FROM public."User" 
            WHERE auth_id = auth.uid()
        )
    );

CREATE POLICY "Users can insert their own metrics"
    ON UserMetricsHistory
    FOR INSERT
    WITH CHECK (
        user_id IN (
            SELECT id FROM public."User" 
            WHERE auth_id = auth.uid()
        )
    );

-- Create index for faster querying by user and date
CREATE INDEX IF NOT EXISTS idx_metrics_user_date ON UserMetricsHistory(user_id, recorded_at);
