


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  INSERT INTO public."User" (email, fullname, username, auth_id)
  VALUES (
    new.email, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'username', 
    new.id
  );
  RETURN new;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Calendar" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "user_id" bigint,
    "date" "date",
    "notes" "text",
    "status" boolean DEFAULT false,
    "recipe_id" bigint,
    "updated_at" timestamp with time zone,
    "meal_type" "text" DEFAULT 'dinner'::"text" NOT NULL
);


ALTER TABLE "public"."Calendar" OWNER TO "postgres";


COMMENT ON COLUMN "public"."Calendar"."meal_type" IS 'Meal type: breakfast, lunch, or dinner';



ALTER TABLE "public"."Calendar" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Calendar_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Ingredient" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "name" "text",
    "unit" "text" NOT NULL,
    "agg_fats_g" numeric,
    "agg_minerals_mg" numeric,
    "agg_vit_b_mg" numeric,
    "calories_kcal" numeric,
    "carbs_g" numeric,
    "cholesterol_mg" numeric,
    "protein_g" numeric,
    "sugars_g" numeric,
    "vit_a_microg" numeric,
    "vit_c_mg" numeric,
    "vit_d_microg" numeric,
    "vit_e_mg" numeric,
    "vit_k_microg" numeric
);


ALTER TABLE "public"."Ingredient" OWNER TO "postgres";


ALTER TABLE "public"."Ingredient" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Ingredient_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Recipe" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "name" "text",
    "description" "text",
    "image_url" "text",
    "min_prep_time" integer,
    "green_score" numeric,
    "updated_at" timestamp with time zone,
    "owner_id" bigint
);


ALTER TABLE "public"."Recipe" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Recipe-Calendar_Map" (
    "id" bigint NOT NULL,
    "calendar_id" bigint,
    "recipe_id" bigint
);


ALTER TABLE "public"."Recipe-Calendar_Map" OWNER TO "postgres";


ALTER TABLE "public"."Recipe-Calendar_Map" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Recipe-Calendar_Map_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Recipe-Ingredient_Map" (
    "id" bigint NOT NULL,
    "recipe_id" bigint,
    "ingredient_id" bigint,
    "relative_unit_100" numeric
);


ALTER TABLE "public"."Recipe-Ingredient_Map" OWNER TO "postgres";


ALTER TABLE "public"."Recipe-Ingredient_Map" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Recipe-Ingredient_Map_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Recipe-Tag_Map" (
    "id" bigint NOT NULL,
    "recipe_id" bigint,
    "tag_id" bigint
);


ALTER TABLE "public"."Recipe-Tag_Map" OWNER TO "postgres";


ALTER TABLE "public"."Recipe-Tag_Map" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Recipe-Tag_Map_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."RecipeTag" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "name" "text",
    "description" "text"
);


ALTER TABLE "public"."RecipeTag" OWNER TO "postgres";


ALTER TABLE "public"."RecipeTag" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."RecipeTag_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Recipe" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Recipe_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."User" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "email" "text",
    "fullname" "text",
    "password_hash" "text",
    "updated_at" timestamp with time zone,
    "username" "text",
    "auth_id" "uuid"
);


ALTER TABLE "public"."User" OWNER TO "postgres";


COMMENT ON TABLE "public"."User" IS 'Public user profile data';



ALTER TABLE "public"."User" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."User_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Calendar"
    ADD CONSTRAINT "Calendar_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Ingredient"
    ADD CONSTRAINT "Ingredient_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Recipe-Calendar_Map"
    ADD CONSTRAINT "Recipe-Calendar_Map_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Recipe-Ingredient_Map"
    ADD CONSTRAINT "Recipe-Ingredient_Map_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Recipe-Tag_Map"
    ADD CONSTRAINT "Recipe-Tag_Map_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."RecipeTag"
    ADD CONSTRAINT "RecipeTag_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Recipe"
    ADD CONSTRAINT "Recipe_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."User"
    ADD CONSTRAINT "User_auth_id_key" UNIQUE ("auth_id");



ALTER TABLE ONLY "public"."User"
    ADD CONSTRAINT "User_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Calendar"
    ADD CONSTRAINT "Calendar_recipe_id_fkey" FOREIGN KEY ("recipe_id") REFERENCES "public"."Recipe"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Calendar"
    ADD CONSTRAINT "Calendar_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."User"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Recipe-Calendar_Map"
    ADD CONSTRAINT "Recipe-Calendar_Map_calendar_id_fkey" FOREIGN KEY ("calendar_id") REFERENCES "public"."Calendar"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Recipe-Calendar_Map"
    ADD CONSTRAINT "Recipe-Calendar_Map_recipe_id_fkey" FOREIGN KEY ("recipe_id") REFERENCES "public"."Recipe"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Recipe-Ingredient_Map"
    ADD CONSTRAINT "Recipe-Ingredient_Map_ingredient_id_fkey" FOREIGN KEY ("ingredient_id") REFERENCES "public"."Ingredient"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Recipe-Ingredient_Map"
    ADD CONSTRAINT "Recipe-Ingredient_Map_recipe_id_fkey" FOREIGN KEY ("recipe_id") REFERENCES "public"."Recipe"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Recipe-Tag_Map"
    ADD CONSTRAINT "Recipe-Tag_Map_recipe_id_fkey" FOREIGN KEY ("recipe_id") REFERENCES "public"."Recipe"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Recipe-Tag_Map"
    ADD CONSTRAINT "Recipe-Tag_Map_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."RecipeTag"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Recipe"
    ADD CONSTRAINT "Recipe_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."User"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."User"
    ADD CONSTRAINT "User_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id");



CREATE POLICY "Authenticated users can create recipes" ON "public"."Recipe" FOR INSERT WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



ALTER TABLE "public"."Calendar" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Ingredient" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Ingredients are viewable by everyone" ON "public"."Ingredient" FOR SELECT USING (true);



ALTER TABLE "public"."Recipe" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Recipe-Calendar Map viewable by owner" ON "public"."Recipe-Calendar_Map" FOR SELECT USING (("calendar_id" IN ( SELECT "Calendar"."id"
   FROM "public"."Calendar"
  WHERE ("Calendar"."user_id" IN ( SELECT "User"."id"
           FROM "public"."User"
          WHERE ("User"."auth_id" = "auth"."uid"()))))));



ALTER TABLE "public"."Recipe-Calendar_Map" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Recipe-Ingredient Map viewable by everyone" ON "public"."Recipe-Ingredient_Map" FOR SELECT USING (true);



ALTER TABLE "public"."Recipe-Ingredient_Map" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Recipe-Tag Map viewable by everyone" ON "public"."Recipe-Tag_Map" FOR SELECT USING (true);



ALTER TABLE "public"."Recipe-Tag_Map" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."RecipeTag" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Recipes are viewable by everyone" ON "public"."Recipe" FOR SELECT USING (true);



CREATE POLICY "Tags are viewable by everyone" ON "public"."RecipeTag" FOR SELECT USING (true);



ALTER TABLE "public"."User" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Users can delete from their own calendar" ON "public"."Calendar" FOR DELETE USING (("user_id" IN ( SELECT "User"."id"
   FROM "public"."User"
  WHERE ("User"."auth_id" = "auth"."uid"()))));



CREATE POLICY "Users can insert into their own calendar" ON "public"."Calendar" FOR INSERT WITH CHECK (("user_id" IN ( SELECT "User"."id"
   FROM "public"."User"
  WHERE ("User"."auth_id" = "auth"."uid"()))));



CREATE POLICY "Users can update their own calendar" ON "public"."Calendar" FOR UPDATE USING (("user_id" IN ( SELECT "User"."id"
   FROM "public"."User"
  WHERE ("User"."auth_id" = "auth"."uid"()))));



CREATE POLICY "Users can update their own profile" ON "public"."User" FOR UPDATE USING (("auth_id" = "auth"."uid"()));



CREATE POLICY "Users can update their own recipes" ON "public"."Recipe" FOR UPDATE USING (("owner_id" IN ( SELECT "User"."id"
   FROM "public"."User"
  WHERE ("User"."auth_id" = "auth"."uid"()))));



CREATE POLICY "Users can view their own calendar" ON "public"."Calendar" FOR SELECT USING (("user_id" IN ( SELECT "User"."id"
   FROM "public"."User"
  WHERE ("User"."auth_id" = "auth"."uid"()))));



CREATE POLICY "Users can view their own profile" ON "public"."User" FOR SELECT USING (("auth_id" = "auth"."uid"()));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."Calendar" TO "anon";
GRANT ALL ON TABLE "public"."Calendar" TO "authenticated";
GRANT ALL ON TABLE "public"."Calendar" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Calendar_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Calendar_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Calendar_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Ingredient" TO "anon";
GRANT ALL ON TABLE "public"."Ingredient" TO "authenticated";
GRANT ALL ON TABLE "public"."Ingredient" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Ingredient_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Ingredient_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Ingredient_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Recipe" TO "anon";
GRANT ALL ON TABLE "public"."Recipe" TO "authenticated";
GRANT ALL ON TABLE "public"."Recipe" TO "service_role";



GRANT ALL ON TABLE "public"."Recipe-Calendar_Map" TO "anon";
GRANT ALL ON TABLE "public"."Recipe-Calendar_Map" TO "authenticated";
GRANT ALL ON TABLE "public"."Recipe-Calendar_Map" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Recipe-Calendar_Map_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Recipe-Calendar_Map_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Recipe-Calendar_Map_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Recipe-Ingredient_Map" TO "anon";
GRANT ALL ON TABLE "public"."Recipe-Ingredient_Map" TO "authenticated";
GRANT ALL ON TABLE "public"."Recipe-Ingredient_Map" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Recipe-Ingredient_Map_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Recipe-Ingredient_Map_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Recipe-Ingredient_Map_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Recipe-Tag_Map" TO "anon";
GRANT ALL ON TABLE "public"."Recipe-Tag_Map" TO "authenticated";
GRANT ALL ON TABLE "public"."Recipe-Tag_Map" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Recipe-Tag_Map_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Recipe-Tag_Map_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Recipe-Tag_Map_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."RecipeTag" TO "anon";
GRANT ALL ON TABLE "public"."RecipeTag" TO "authenticated";
GRANT ALL ON TABLE "public"."RecipeTag" TO "service_role";



GRANT ALL ON SEQUENCE "public"."RecipeTag_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."RecipeTag_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."RecipeTag_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Recipe_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Recipe_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Recipe_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."User" TO "anon";
GRANT ALL ON TABLE "public"."User" TO "authenticated";
GRANT ALL ON TABLE "public"."User" TO "service_role";



GRANT ALL ON SEQUENCE "public"."User_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."User_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."User_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


